---
title: "ODS Topic Modelling"
author: "Tim Foster"
date: "2022-11-10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Get the metedata


```{r cars, message=FALSE, warning=FALSE}
install.packages(opendatascotland)
install.packages(tidyverse)
install.packages(topicmodels)
install.packages(tidytext)
install.packages(tm)
install.packages(SnowballC)
install.packages(rvest)
install.packages(reticulate)
library(opendatascotland)
library(tidyverse)
library(topicmodels)
library(tidytext)
library(tm)
library(SnowballC)
library(rvest)
library(reticulate)

metadata <- search_ods()

strip_html <- function(s) {
    html_text(read_html(s))
}
  
notes <- metadata$notes

description <- notes %>% purrr::map(function(x) {
  if(is.na(x)) {
    return(NULL)
  }
  d <- strip_html(x)
  return(d)
})
metadata$description <- description
glimpse(metadata)
```

## Topic Model

```{r pressure, echo=TRUE, message=FALSE, warning=FALSE}
# function to get & plot the most informative terms by a specificed number
# of topics, using LDA
top_terms_by_topic_LDA <- function(input_text, # should be a columm from a dataframe
                                   plot = T, # return a plot? TRUE by defult
                                   number_of_topics = 4) # number of topics (4 by default)
{    

  input_text <- data.frame(input_text)
  if( nrow(input_text) != 1) {
    return(NULL)
  }
    # create a corpus (type of object expected by tm) and document term matrix
    Corpus <- Corpus(VectorSource(input_text)) # make a corpus object
    DTM <- DocumentTermMatrix(Corpus) # get the count of words/document

    # remove any empty rows in our document term matrix (if there are any 
    # we'll get an error when we try to run our LDA)
    unique_indexes <- unique(DTM$i) # get the index of each unique value
    DTM <- DTM[unique_indexes,] # get a subset of only those indexes
    
    # preform LDA & get the words/topic in a tidy text format
    lda <- LDA(DTM, k = number_of_topics, control = list(seed = 1234))
    topics <- tidy(lda, matrix = "beta")

    # get the top ten terms for each topic
    top_terms <- topics  %>% # take the topics data frame and..
      group_by(topic) %>% # treat each topic as a different group
      top_n(10, beta) %>% # get the top 10 most informative words
      ungroup() %>% # ungroup
      arrange(topic, -beta) # arrange words in descending informativeness

    # if the user asks for a plot (TRUE by default)
    # if(plot == T){
    #   if(is.null(term)) {
    #     return(NULL)
    #   }
    #     # plot the top ten terms for each topic in order
    #     top_terms %>% # take the top terms
    #       mutate(term = reorder(term, beta)) %>% # sort terms by beta value 
    #       ggplot(aes(term, beta, fill = factor(topic))) + # plot beta by theme
    #       geom_col(show.legend = FALSE) + # as a bar plot
    #       facet_wrap(~ topic, scales = "free") + # which each topic in a seperate plot
    #       labs(x = NULL, y = "Beta") + # no x label, change y label 
    #       coord_flip() # turn bars sideways
    # }else{ 
        # if the user does not request a plot
        # return a list of sorted terms instead
        return(top_terms)
    # }
}





```



## Clean stop words

```{r}
reviewsCorpus <- Corpus(VectorSource(metadata$description)) 
reviewsDTM <- DocumentTermMatrix(reviewsCorpus)

# convert the document term matrix to a tidytext corpus
reviewsDTM_tidy <- tidy(reviewsDTM)

# I'm going to add my own custom stop words that I don't think will be
# very informative in hotel reviews
custom_stop_words <- tibble(word = c("hotel", "room"))

# remove stopwords
reviewsDTM_tidy_cleaned <- reviewsDTM_tidy %>% # take our tidy dtm and...
    anti_join(stop_words, by = c("term" = "word")) %>% # remove English stopwords and...
    anti_join(custom_stop_words, by = c("term" = "word")) # remove my custom stopwords

# reconstruct cleaned documents (so that each word shows up the correct number of times)
cleaned_documents <- reviewsDTM_tidy_cleaned %>%
    group_by(document) %>% 
    mutate(terms = toString(rep(term, count))) %>%
    select(document, terms) %>%
    unique()

# check out what the cleaned documents look like (should just be a bunch of content words)
# in alphabetic order
head(cleaned_documents)


topics <- cleaned_documents$terms %>% purrr::map(top_terms_by_topic_LDA)

metadata$topics <- topics

topics_df <- metadata %>% unnest(cols = c("title", "topics")) 
topics_df <- topics_df %>% select(title, term)

test <- topics_df[!duplicated(topics_df$term),]

```

# Categories



```{python}

# Set association between dataset tag and ODS category
  ods_categories = {
            "Arts / Culture / History": [
                "arts",
                "culture",
                "history",
                "military",
                "art gallery",
                "design",
                "fashion",
                "museum",
                "historic centre",
                "conservation",
                "archaeology",
                "events",
                "theatre",
            ],
            "Budget / Finance": [
                "tenders",
                "contracts",
                "lgcs finance",
                "budget",
                "finance",
                "payment",
                "grants",
                "financial year",
                "council tax",
            ],
            "Business and Economy": [
                "business and economy",
                "business",
                "business and trade",
                "economic information",
                "economic development",
                "business grants",
                "business awards",
                "health and safety",
                "trading standards",
                "food safety",
                "business rates",
                "commercial land and property" "commercial waste",
                "pollution",
                "farming",
                "forestry",
                "crofting",
                "countryside",
                "farming",
                "emergency planning",
                "health and safety",
                "trading standards",
                "health and safety at work",
                "regeneration",
                "shopping",
                "shopping centres",
                "markets",
                "tenders",
                "contracts",
                "city centre management",
                "town centre management",
                "economy",
                "economic",
                "economic activity",
                "economic development",
                "deprivation",
                "scottish index of multiple deprivation",
                "simd",
                "business",
                "estimated population",
                "population",
                "labour force",
            ],
            "Council and Government": [
                "council buildings",
                "community development",
                "council and government",
                "council",
                "councils",
                "council tax",
                "benefits",
                "council grants",
                "grants",
                "council departments",
                "data protection",
                "FOI",
                "freedom of information",
                "council housing",
                "politicians",
                "MPs",
                "MSPs",
                "councillors",
                "elected members",
                "wards",
                "constituencies",
                "boundaries",
                "council minutes",
                "council agendas",
                "council plans",
                "council policies",
            ],
            "Education": [
                "primary schools",
                "lgcs education & skills",
                "education",
                "eductional",
                "library",
                "school meals",
                "schools",
                "school",
                "nurseries",
                "playgroups",
            ],
            "Elections / Politics": [
                "community councils",
                "political",
                "polling places",
                "elections",
                "politics",
                "elecorate",
                "election",
                "electoral",
                "electorate",
                "local authority",
                "council area",
                "democracy",
                "polling",
                "lgcs democracy",
                "democracy and governance",
                "local government",
                "councillor",
                "councillors",
                "community council",
            ],
            "Food and Environment": [
                "food",
                "school meals",
                "allotment",
                "public toilets",
                "air",
                "tree",
                "vacant and derelict land supply",
                "landscape",
                "nature",
                "rights of way",
                "tree preservation order",
                "preservation",
                "land",
                "contaminated",
                "green",
                "belt",
                "employment land audit",
                "environment",
                "forest woodland strategy",
                "waste",
                "recycling",
                "lgcs waste management",
                "water-network",
                "grafitti",
                "street occupations",
                "regeneration",
                "vandalism",
                "street cleansing",
                "litter",
                "toilets",
                "drains",
                "flytipping",
                "flyposting",
                "pollution",
                "air quality",
                "household waste",
                "commercial waste",
            ],
            "Health and Social Care": [
                "public toilets",
                "contraception",
                "implant",
                "cervical",
                "iud",
                "ius",
                "pis",
                "prescribing",
                "elderly",
                "screening",
                "screening programme",
                "cancer",
                "breast feeding",
                "defibrillators",
                "wards",
                "alcohol and drug partnership",
                "care homes",
                "waiting times",
                "drugs",
                "substance use",
                "pregnancy",
                "induced abortion",
                "therapeutic abortion",
                "termination",
                "abortion",
                "co-dependency",
                "sexual health",
                "outpatient",
                "waiting list",
                "stage of treatment",
                "daycase",
                "inpatient",
                "alcohol",
                "waiting time",
                "treatment",
                "community wellbeing and social environment",
                "health",
                "human services",
                "covid-19",
                "covid",
                "hospital",
                "health board",
                "health and social care partnership",
                "medicine",
                "health and social care",
                "health and fitness",
                "nhs24",
                "hospital admissions",
                "hospital mortality",
                "mental health",
                "pharmacy",
                "GP",
                "surgery",
                "fostering",
                "adoption",
                "social work",
                "asylum",
                "immigration",
                "citizenship",
                "carers",
            ],
            "Housing and Estates": [
                "buildings",
                "housing data supply 2020",
                "multiple occupation",
                "housing",
                "sheltered housing",
                "adaptations",
                "repairs",
                "council housing",
                "landlord",
                "landlord registration",
                "rent arrears",
                "parking",
                "garages",
                "homelessness",
                "temporary accommodation",
                "rent",
                "tenancy",
                "housing advice",
                "housing associations",
                "housing advice",
                "housing repairs",
                "lettings",
                "real estate",
                "land records",
                "land-cover",
                "woodland",
                "dwellings",
                "burial grounds",
                "cemeteries",
                "property",
                "vacant and derelict land",
                "scottish vacant and derelict land",
                "allotment",
            ],
            "Law and Licensing": [
                "law",
                "licensing",
                "regulation",
                "regulations",
                "licence",
                "licenses",
                "permit",
                "permits",
                "police",
                "court",
                "courts",
                "tribunal",
                "tribunals",
            ],
            "Parks / Recreation": [
                "parks",
                "recreation",
                "woodland",
                "parks and open spaces",
            ],
            "Planning and Development": [
                "buildings",
                "vacant and derelict land supply",
                "core paths. adopted",
                "employment land audit",
                "built environment",
                "planning",
                "zoning",
                "council area",
                "address",
                "addresses",
                "city development plan",
                "boundaries",
                "post-code",
                "dwellings",
                "planning permission",
                "postcode-units",
                "housing",
                "property",
                "building control",
                "conservation",
            ],
            "Public Safety": [
                "emergency planning",
                "public safety",
                "crime and justice",
                "lgcs community safety",
                "street lighting",
                "community safety",
                "cctv",
                "road safety",
            ],
            "Sport and Leisure": [
                "sport",
                "sports",
                "sports facilities",
                " sports activities",
                "countryside",
                "wildlife",
                "leisure",
                "leisure clubs",
                "clubs",
                "groups",
                "societies",
                "libraries",
                "archives",
                "local history",
                "heritage",
                "museums",
                "galleries",
                "parks",
                "gardens",
                "open spaces",
                "sports",
                "sports clubs",
                "leisure centres",
            ],
            "Tourism": [
                "public toilets",
                "tourism",
                "tourist",
                "attractions",
                "accomodation",
                "historic buildings",
                "tourist routes",
                "cafes",
                "restaurants",
                "hotels",
                "hotel",
            ],
            "Transportation": [
                "core paths. adopted",
                "lgcs transport infrastructure",
                "transportation",
                "mobility",
                "pedestrian",
                "walking",
                "walk",
                "cycle",
                "cycling",
                "parking",
                "car",
                "bus",
                "tram",
                "train",
                "taxi",
                "transport",
                "electric vehicle",
                "electric vehicle charging points",
                "transport / mobility",
                "active travel",
                "road safety",
                "roads",
                "community transport",
                "road works",
                "road closures",
                "speed limits",
                "port",
                "harbour",
            ],
        }
```

# Check against current categories

```{r}

  ods_categories <- py$ods_categories 
  ods_categories <- stack(ods_categories)
  test$term <- gsub("[,;.()\"`‘]", "", test$term)
  merged_output <- read_csv("~/Documents/projects/the_od_bods/data/merged_output.csv")
original_tags <- select(merged_output, Title, OriginalTags)
 original_tags <- separate(original_tags, OriginalTags, into = c("a","b","c","d","e","f","g","h","i","j","k","l","m"), sep = ";")
    original_tags <- pivot_longer(original_tags, 
                                cols = c(a,b,c,d,e,f,g,h,i,j,k,l,m),
                                values_to = "term"
                                )
   original_tags <-  na.omit(original_tags) %>% select("title" = Title, term)
   test <- bind_rows(test, original_tags)
    
  ods_categories_auto <- inner_join(test, ods_categories, by = c("term" = "values"))
  

  merged_output <- select(merged_output, Title, ODSCategories)

  merged_output <- separate(merged_output, ODSCategories, into = c("a","b","c","d","e","f","g","h","i","j","k","l","m"), sep = ";")
    merged_output <- pivot_longer(merged_output, 
                                cols = c(a,b,c,d,e,f,g,h,i,j,k,l,m),
                                values_to = "ods_term"
                                )
  merged_output <-  na.omit(merged_output) %>% select(Title, ods_term)
  
  merge_auto <- left_join(merged_output, ods_categories_auto, 
                           by = c("Title" = "title"))
  
  merge_auto <- select(merge_auto, Title, ods_term, ind) %>% unique()
```

Present current Vs AI enhanced auto-categorization

```{r}
merge_auto$ind <- as.character(merge_auto$ind)
merge_auto %>% split(merge_auto$Title) %>% map_df(function(x) {
  browser()
  x <- mutate(x, ods_term = ifelse(ods_term != ind & !is.na(ind),
                                   NA, ods_term))
  
  x <- mutate(x, ind = ifelse(ind != ods_term & !is.na(ods_term),
                                   NA, ind))  
  x <- arrange(x, ind,  ods_term)
  x <- x[!duplicated(x$ind  , incomparables = NA), ]

  return(x)
})


```

